apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  labels:
    app: simple-webapp
spec:
  ports:
  - port: 80
    name: simple-webapp
    targetPort: 80
  type: ClusterIP
  selector:
    app: simple-webapp
