apiVersion: v1
kind: Service
metadata:
  name: simple-webapp
  labels:
    app: simple-webapp
spec:
  ports:
  - port: {{ .Values.SWA.Port }}
    name: simple-webapp
    targetPort: {{ .Values.SWA.Port }}
  type: ClusterIP
  selector:
    app: simple-webapp
